## file: app.http

## Global Variables
@baseUrl = http://localhost:5000

# @name PostPrediction
POST {{baseUrl}}/predict
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="file.jpg"
Content-Type: image/jpg

< .archives/file.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###

# Response
{
  "filename": "file.jpg",
  "prediction": [
    {
      "box": [
        199.2130126953125,
        106.84730529785156,
        521.3106689453125,
        561.7120361328125
      ],
      "confidence": 0.9994798302650452,
      "label": "kirin_mentah"
    }
  ]
}
###